APP:
  addr: 8080
  pprof: 8081
  mode: dev
  name: Go-backendapi

JWT:
  expireTime: 7200
  secret: 123456
  audience: Go-Admin

DB:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root@123456
  dbname: test

REDIS:
  addr: 127.0.0.1:6379
  password: ""
  db: 0

LOG:
  level: DEBUG
  filepath: '../app.log'
  filemaxsize: 5
  filemaxage: 30
  maxbackups: 10
  compress: true

KAFKA:
  mode: DEBUG
  addr:
    - 127.0.0.1:8090
  enable: false
  topics: log
  requiredack: 1

Email:
  subject: Notice
  smtphost: smtp.qq.com
  smtp: 25
  sender: 931883200@qq.com
  receiver:
    - liyaoo1995@163.com
  code: fdegdnvvnibhbdcf
  call: "<a href='http://127.0.0.1/api/v1/verifyemail'>%s</a>"





